
{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "userserviceui.fullname" . }}
  labels:
    {{- include "userserviceui.labels" . | nindent 4 }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ tpl .Values.istio.ingressGateway . }}
  http:
  - name: "authservice"
    match:
    - uri:
        prefix: "/authentication"
    - uri:
        prefix: "/.well-known"
    route:
    - destination:
        host: {{ include "authservice.fullname" .Subcharts.authservice }}
        port:
          number: {{ .Values.authservice.service.port }}
      weight: 100
  - name: "userservice"
    match:
    - uri:
        prefix: "/api/user"
    route:
    - destination:
        host: {{ include "userservice.fullname" .Subcharts.userservice }}
        port:
          number: {{ .Values.userservice.service.port }}
      weight: 100
  - route:
    - destination:
        host: {{ include "userserviceui.fullname" . }}
        port:
          number: {{ .Values.service.port }}
      weight: 100
{{- end }}